version: 2

seeds:
  - name: employees
    description: a manual map of employeesto customers
    columns: 
      - name: employee_id
        tests:
            - unique
            - not_null